### ISSUE TITLE
Updating TRestRawVetoAnalysisProcess and adding TRestRawVetoCalibrationProcess

### ISSUE THREAD

**Issue by KonradAltenmueller** [rest-for-physics/rawlib#32]
I thought about following changes to the veto analysis and adding a process for the veto calibration:

- changing the way how veto groups are handled by `TRestRawVetoAnalysisProcess`: keep only two observables `veto_PeakTime` and `veto_MaxPeakAmplitude`, where each is a `std::map` with all veto signal IDs as keys, rather than two observables for each group. This makes further processing simpler.
- Adding an optional parameter, that contains a `std::map` which defines the veto groups, e.g `<1234, "top_1">`  and can be read out when necessary for the analysis / plotting
- Adding a process `TRestRawVetoCalibrationProcess` which adds an observable with the calibrated veto amplitudes. The calibration factors can be defined in the rml, or can be loaded from some public file. In this process also the veto groups can be defined.
- The calibration itself (to obtain the calibration factors) is done offline, but I can share the macro later in the iaxo-analysis git.

Does this sound good to you, or has anyone suggestions to do it differently?

**Comment by jgalan** [comment]
In point 1. what do you mean with all veto signal IDs as keys?

It is this perhaps what it is being executed at the following pipeline?

```
analysisProcess: 
  type: process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/processes/analysis
    - restManager --c veto.rml --f ../../data/R01208_Ar2Iso_Background14h_14Vetos_IccubFEC-000.aqs
    - restRoot -b -q validate.C
```

https://gitlab.cern.ch/rest-for-physics/rawlib/-/blob/master/pipeline/processes/analysis/veto.rml

That will create a `std::map` with all veto signals, extracting only the `peakTime` and the `maxAmplitude`.

Not sure about point 2. Perhaps it is connected with issue #64? I believe something like that would allow us to have a generic way to group the `std::map.first` elements. But probably we could design a new tool that allows to do that kind of analysis, no need to be a REST process. The idea/philosophy is that the data processing chain is only executed once, or twice. If this is not the case right now is because it is yet under development, not other reason.

We must make the difference between *data processing* and *data analysis*. During the *data processing* we extract all the necessary information so that later on we are able to create tools that allow us to do the analysis, by means of c++ classes, ROOT macros, or other means.

So, for point 3. do you think you will need to apply calibration corrections/renormalization already during the *data processing*?
